export type UserRole = 'admin' | 'user' | 'klant';

export interface AppointmentType {
  id: string;
  name: string;
  duration_minutes: number;
  description: string | null;
  requires_package: boolean;
  max_per_user: number | null;
  color: string;
  active: boolean;
  sort_order: number;
}

export interface WorkingHour {
  day_of_week: number; // 0=Sun … 6=Sat
  start_time: string;  // 'HH:MM'
  end_time: string;
  is_active: boolean;
  break_start: string | null;
  break_end: string | null;
}

export interface Appointment {
  id: string;
  user_id: string | null;       // null for guest bookings from contact page
  guest_name: string | null;    // populated when user_id is null
  guest_email: string | null;
  appointment_type_id: string | null;
  type_name: string;
  duration_minutes: number;
  starts_at: string;
  ends_at: string;
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'no_show';
  notes: string | null;
  admin_notes: string | null;
  meeting_link: string | null;
  location: string | null;
  cancellation_reason: string | null;
  color: string;
  created_at: string;
  updated_at: string;
  // joined (only when user has an account)
  profile?: {
    full_name: string | null;
    email: string;
  } | null;
}

export interface TimeLog {
  id: string;
  user_id: string;
  logged_date: string;
  duration_minutes: number;
  description: string | null;
  billable: boolean;
  created_at: string;
  // joined
  profile?: {
    full_name: string | null;
    email: string;
  };
}

export interface PackageRequest {
  id: string;
  user_id: string | null;
  package_name: string;
  package_price: number;
  status: 'pending' | 'contacted' | 'accepted' | 'rejected';
  notes: string | null;
  admin_notes: string | null;
  // guest fields (unauthenticated leads)
  guest_name: string | null;
  guest_email: string | null;
  guest_phone: string | null;
  guest_company: string | null;
  created_at: string;
  updated_at: string;
  // joined (authenticated users only)
  profile?: {
    full_name: string | null;
    email: string;
    company: string | null;
    phone: string | null;
  };
}

export type BillingInterval = 'one_time' | 'monthly' | 'yearly';

export interface Package {
  id: string;
  name: string;
  price: number;
  description: string;
  features: string[];
  color: string;
  highlight: boolean;
  active: boolean;
  sort_order: number;
  billing_interval: BillingInterval;
  created_at: string;
  updated_at: string;
}

export type DossierStatus = 'lead' | 'prospect' | 'klant' | 'completed';
export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
export type ActivityType  = 'appointment_created' | 'package_request' | 'invoice_created' | 'status_change' | 'message_sent';

export interface ClientDossier {
  id: string;
  profile_id: string | null;
  status: DossierStatus;
  notes: string | null;
  // guest lead fields (no Supabase account)
  guest_name: string | null;
  guest_email: string | null;
  guest_phone: string | null;
  guest_company: string | null;
  source: 'manual' | 'package_request' | null;
  created_at: string;
  updated_at: string;
  // joined
  profile?: {
    id?: string;
    full_name: string | null;
    email: string;
    phone: string | null;
    company: string | null;
    customer_number: number | null;
    vat_number?: string | null;
    address?: string | null;
    postal_code?: string | null;
    city?: string | null;
  };
  packages?: DossierPackage[];
}

export interface DossierPackage {
  id: string;
  dossier_id: string;
  package_id: string;
  is_active: boolean;
  is_recurring: boolean;
  started_at: string;
  created_at: string;
  // joined
  package?: {
    id: string;
    name: string;
    price: number;
    color: string;
  };
}

export interface ActivityLog {
  id: string;
  profile_id: string | null;
  dossier_id: string | null;
  type: ActivityType;
  title: string;
  metadata: Record<string, unknown>;
  created_at: string;
  // joined
  profile?: { full_name: string | null; email: string } | null;
}

export interface Invoice {
  id: string;
  invoice_number: string;
  dossier_id: string | null;
  /** Null when the invoice was created for a guest client (no Supabase account). */
  profile_id: string | null;
  status: InvoiceStatus;
  issue_date: string;
  due_date: string;
  subtotal: number;
  vat_rate: number;
  vat_amount: number;
  total: number;
  notes: string | null;
  language: 'nl' | 'en';
  is_recurring: boolean;
  recurring_interval: 'monthly' | 'quarterly' | 'yearly' | null;
  /** Date the recurring series began (= issue_date of the first invoice). */
  recurring_start_date: string | null;
  /** Date the next invoice copy should be auto-generated by the cron job. */
  recurring_next_date: string | null;
  // Guest client fields — populated when profile_id is null
  guest_name: string | null;
  guest_email: string | null;
  guest_company: string | null;
  guest_vat_number: string | null;
  guest_address: string | null;
  guest_postal_code: string | null;
  guest_city: string | null;
  created_at: string;
  updated_at: string;
  // joined
  profile?: { full_name: string | null; email: string; company: string | null; vat_number: string | null; address: string | null; postal_code: string | null; city: string | null } | null;
  items?: InvoiceItem[];
}

export interface InvoiceItem {
  id: string;
  invoice_id: string;
  description: string;
  notes: string | null;
  quantity: number;
  unit_price: number;
  total: number;
  package_id: string | null;
  created_at: string;
}

// ─── Contracts ────────────────────────────────────────────────────────────────

export type ContractServiceType = 'website' | 'hosting' | 'domain' | 'other';
export type ContractStatus      = 'active' | 'cancelled';

export interface Contract {
  id: string;
  contract_number: string;
  // Client linkage
  dossier_id: string | null;
  profile_id: string | null;
  // Guest client fields
  guest_name: string | null;
  guest_email: string | null;
  guest_company: string | null;
  guest_vat_number: string | null;
  guest_address: string | null;
  guest_postal_code: string | null;
  guest_city: string | null;
  // Service
  service_type: ContractServiceType;
  service_description: string;
  // Pricing
  monthly_price_excl_vat: number;
  vat_rate: number;
  // Dates
  start_date: string;
  first_invoice_date: string;
  // Status & cancellation
  status: ContractStatus;
  notice_period_months: number;
  cancellation_date: string | null;
  cancellation_reason: string | null;
  // Linked invoice
  recurring_invoice_id: string | null;
  // Document
  contract_text: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  // Joined relations
  profile?: { full_name: string | null; email: string; company: string | null; vat_number: string | null; address: string | null; postal_code: string | null; city: string | null } | null;
  dossier?: { id: string; guest_name: string | null; guest_email: string | null; guest_company: string | null } | null;
}

export interface NotificationPreferences {
  email_messages?: boolean;
  email_invoices?: boolean;
  email_appointments?: boolean;
  newsletter?: boolean;
}

export interface Profile {
  id: string;
  email: string;
  full_name: string | null;
  phone?: string | null;
  company?: string | null;
  vat_number?: string | null;
  address?: string | null;
  postal_code?: string | null;
  city?: string | null;
  country?: string | null;
  profile_picture_url?: string | null;
  public_username?: string | null;
  customer_number?: number | null;
  show_public_email?: boolean | null;
  show_public_company?: boolean | null;
  show_public_location?: boolean | null;
  show_public_review?: boolean | null;
  review_score?: number | null;
  review_text?: string | null;
  notification_preferences?: NotificationPreferences | null;
  role: UserRole;
  created_at: string;
  updated_at?: string;
}
